name: IanSandersonArt
favicon: null
layout_spectrum: 0.30916527402587235
typography_spectrum: 0.347091207979247
title: Gum Bichromate Prints
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.7683559346478432
purpose: []
